version: "3"
services:
  app:
    build: .
    container_name: twitter_manager_app
    volumes:
      - ./run.sh:/app/run.sh
      - ./main.py:/app/main.py
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
    restart: always
